# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        TeamupBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: TeamupBundle:User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            logout:
                invalidate_session: true
                path:   /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login_check
            switch_user: {role: ROLE_ADMIN, parameter: impersonate}

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/$, roles: ROLE_ADMIN }
        - { path: ^/user/new$, roles: ROLE_ADMIN }
        - { path: ^/user/$, roles: ROLE_ADMIN }
        - { path: ^/user/reportUsers/PwzmEY3cn9FDV2wJwGeWSMRCzauHQg$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: ROLE_USER }
        - { path: ^/interest, roles: ROLE_ADMIN }
        - { path: ^/invitation, roles: ROLE_USER }
        - { path: ^/message, roles: ROLE_USER }
        - { path: ^/petition, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_ADMIN }
        - { path: ^/team/$, roles: ROLE_ADMIN }
        - { path: ^/team, roles: ROLE_USER }
