<?php

namespace TeamupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
	public function findOthersOfSameRecieverTeam($invitation)
	{
        $senderTeamId = $invitation->getSender()->getTeam()->getId();
        $recieverTeamId = $invitation->getReciever()->getTeam()->getId();

		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM TeamupBundle:Invitation i
                JOIN i.reciever r
                JOIN i.sender s
                JOIN r.team rt
                JOIN s.team st
                WHERE st.id = :senderTeamId AND rt.id = :recieverTeamId
                '
            )->setParameters(array('senderTeamId' => $senderTeamId, 'recieverTeamId' => $recieverTeamId) );
     
        try 
        {
            return $query->getResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
	}
}
