<?php

namespace TeamupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionRepository extends EntityRepository
{
	public function findOthersOfSameSenderTeam($petition)
	{
        $senderTeamId = $petition->getSender()->getTeam()->getId();
        $recieverTeamId = $petition->getReciever()->getTeam()->getId();

		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM TeamupBundle:Petition p
                JOIN p.reciever r
                JOIN p.sender s
                JOIN r.team rt
                JOIN s.team st
                WHERE rt.id = :senderTeamId AND rt.id = :recieverTeamId
                '
            )->setParameters(array('senderTeamId' => $senderTeamId, 'recieverTeamId' => $recieverTeamId) );
     
        try 
        {
            return $query->getResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
	}
}
