<?php

namespace TeamupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
	public function wantedTeams($currentUser)
	{
        $currentId = 0;
        if($currentUser->hasTeam())
        {
            $currentId = $currentUser->getTeam()->getId();
        }
		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT distinct t FROM TeamupBundle:Team t
                INNER JOIN t.users us
                WHERE t.status = 1 AND t.id != :currentId
                '
            )->setParameter('currentId', $currentId);
    
        try 
        {
            return $query->getResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
	}
}
