<?php

namespace TeamupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function wantedUsers($currentUser)
	{
		$query = $this->getEntityManager()
            ->createQuery(
                "SELECT u FROM TeamupBundle:User u
                WHERE u.team IS NULL AND u.id != :currentUserId AND u.role != 'ROLE_ADMIN'
                "
            )->setParameter('currentUserId', $currentUser->getId());
     
        try 
        {
            return $query->getResult();
        } 
        catch (\Doctrine\ORM\NoResultException $e) 
        {
            return null;
        }
	}
}
